import {
  Archive,
  Binary,
  Blocks,
  BookOpen,
  Box,
  Braces,
  Code2,
  Cog,
  Coffee,
  Cpu,
  Database,
  File,
  FileCheck,
  FileCode,
  FileCode2,
  FileSpreadsheet,
  FileText,
  FileType,
  Flame,
  FlaskConical,
  Gem,
  Globe,
  Hash,
  Hexagon,
  Image,
  Lock,
  Music2,
  NotebookPen,
  Palette,
  Scroll,
  Settings,
  Shield,
  SquareFunction,
  Terminal,
  Video,
  Workflow,
} from 'lucide-react';

import type { FileIconData, FileIconMap } from '../types/types';

export const ICON_SIZE_CLASS = 'w-4 h-4 flex-shrink-0';

const FILE_ICON_MAP: FileIconMap = {
  js: { icon: FileCode, color: 'text-warning' },
  jsx: { icon: FileCode, color: 'text-warning' },
  mjs: { icon: FileCode, color: 'text-warning' },
  cjs: { icon: FileCode, color: 'text-warning' },
  ts: { icon: FileCode2, color: 'text-info' },
  tsx: { icon: FileCode2, color: 'text-info' },
  mts: { icon: FileCode2, color: 'text-info' },
  py: { icon: Code2, color: 'text-success' },
  pyw: { icon: Code2, color: 'text-success' },
  pyi: { icon: Code2, color: 'text-success' },
  ipynb: { icon: NotebookPen, color: 'text-warning' },
  rs: { icon: Cog, color: 'text-warning' },
  toml: { icon: Settings, color: 'text-muted-foreground' },
  go: { icon: Hexagon, color: 'text-cyan-500' },
  rb: { icon: Gem, color: 'text-destructive' },
  erb: { icon: Gem, color: 'text-destructive' },
  php: { icon: Blocks, color: 'text-violet-500' },
  java: { icon: Coffee, color: 'text-destructive' },
  jar: { icon: Coffee, color: 'text-destructive' },
  kt: { icon: Hexagon, color: 'text-violet-500' },
  kts: { icon: Hexagon, color: 'text-violet-400' },
  c: { icon: Cpu, color: 'text-info' },
  h: { icon: Cpu, color: 'text-info' },
  cpp: { icon: Cpu, color: 'text-info' },
  hpp: { icon: Cpu, color: 'text-info' },
  cc: { icon: Cpu, color: 'text-info' },
  cs: { icon: Hexagon, color: 'text-purple-600' },
  swift: { icon: Flame, color: 'text-warning' },
  lua: { icon: SquareFunction, color: 'text-info' },
  r: { icon: FlaskConical, color: 'text-info' },
  html: { icon: Globe, color: 'text-warning' },
  htm: { icon: Globe, color: 'text-warning' },
  css: { icon: Hash, color: 'text-info' },
  scss: { icon: Hash, color: 'text-pink-500' },
  sass: { icon: Hash, color: 'text-pink-400' },
  less: { icon: Hash, color: 'text-indigo-500' },
  vue: { icon: FileCode2, color: 'text-success' },
  svelte: { icon: FileCode2, color: 'text-warning' },
  json: { icon: Braces, color: 'text-warning' },
  jsonc: { icon: Braces, color: 'text-warning' },
  json5: { icon: Braces, color: 'text-warning' },
  yaml: { icon: Settings, color: 'text-purple-400' },
  yml: { icon: Settings, color: 'text-purple-400' },
  xml: { icon: FileCode, color: 'text-warning' },
  csv: { icon: FileSpreadsheet, color: 'text-success' },
  tsv: { icon: FileSpreadsheet, color: 'text-success' },
  sql: { icon: Database, color: 'text-info' },
  graphql: { icon: Workflow, color: 'text-pink-500' },
  gql: { icon: Workflow, color: 'text-pink-500' },
  proto: { icon: Box, color: 'text-success' },
  env: { icon: Shield, color: 'text-warning' },
  md: { icon: BookOpen, color: 'text-info' },
  mdx: { icon: BookOpen, color: 'text-info' },
  txt: { icon: FileText, color: 'text-muted-foreground' },
  doc: { icon: FileText, color: 'text-info' },
  docx: { icon: FileText, color: 'text-info' },
  pdf: { icon: FileCheck, color: 'text-destructive' },
  rtf: { icon: FileText, color: 'text-muted-foreground' },
  tex: { icon: Scroll, color: 'text-teal-600' },
  rst: { icon: FileText, color: 'text-muted-foreground' },
  sh: { icon: Terminal, color: 'text-success' },
  bash: { icon: Terminal, color: 'text-success' },
  zsh: { icon: Terminal, color: 'text-success' },
  fish: { icon: Terminal, color: 'text-success' },
  ps1: { icon: Terminal, color: 'text-info' },
  bat: { icon: Terminal, color: 'text-muted-foreground' },
  cmd: { icon: Terminal, color: 'text-muted-foreground' },
  png: { icon: Image, color: 'text-purple-500' },
  jpg: { icon: Image, color: 'text-purple-500' },
  jpeg: { icon: Image, color: 'text-purple-500' },
  gif: { icon: Image, color: 'text-purple-400' },
  webp: { icon: Image, color: 'text-purple-400' },
  ico: { icon: Image, color: 'text-purple-400' },
  bmp: { icon: Image, color: 'text-purple-400' },
  tiff: { icon: Image, color: 'text-purple-400' },
  svg: { icon: Palette, color: 'text-warning' },
  mp3: { icon: Music2, color: 'text-pink-500' },
  wav: { icon: Music2, color: 'text-pink-500' },
  ogg: { icon: Music2, color: 'text-pink-400' },
  flac: { icon: Music2, color: 'text-pink-400' },
  aac: { icon: Music2, color: 'text-pink-400' },
  m4a: { icon: Music2, color: 'text-pink-400' },
  mp4: { icon: Video, color: 'text-rose-500' },
  mov: { icon: Video, color: 'text-rose-500' },
  avi: { icon: Video, color: 'text-rose-500' },
  webm: { icon: Video, color: 'text-rose-400' },
  mkv: { icon: Video, color: 'text-rose-400' },
  ttf: { icon: FileType, color: 'text-destructive' },
  otf: { icon: FileType, color: 'text-destructive' },
  woff: { icon: FileType, color: 'text-destructive' },
  woff2: { icon: FileType, color: 'text-destructive' },
  eot: { icon: FileType, color: 'text-destructive' },
  zip: { icon: Archive, color: 'text-warning' },
  tar: { icon: Archive, color: 'text-warning' },
  gz: { icon: Archive, color: 'text-warning' },
  bz2: { icon: Archive, color: 'text-warning' },
  rar: { icon: Archive, color: 'text-warning' },
  '7z': { icon: Archive, color: 'text-warning' },
  lock: { icon: Lock, color: 'text-muted-foreground' },
  exe: { icon: Binary, color: 'text-muted-foreground' },
  bin: { icon: Binary, color: 'text-muted-foreground' },
  dll: { icon: Binary, color: 'text-muted-foreground' },
  so: { icon: Binary, color: 'text-muted-foreground' },
  dylib: { icon: Binary, color: 'text-muted-foreground' },
  wasm: { icon: Binary, color: 'text-purple-500' },
  ini: { icon: Settings, color: 'text-muted-foreground' },
  cfg: { icon: Settings, color: 'text-muted-foreground' },
  conf: { icon: Settings, color: 'text-muted-foreground' },
  log: { icon: Scroll, color: 'text-muted-foreground' },
  map: { icon: File, color: 'text-muted-foreground' },
};

const FILENAME_ICON_MAP: FileIconMap = {
  Dockerfile: { icon: Box, color: 'text-info' },
  'docker-compose.yml': { icon: Box, color: 'text-info' },
  'docker-compose.yaml': { icon: Box, color: 'text-info' },
  '.dockerignore': { icon: Box, color: 'text-muted-foreground' },
  '.gitignore': { icon: Settings, color: 'text-muted-foreground' },
  '.gitmodules': { icon: Settings, color: 'text-muted-foreground' },
  '.gitattributes': { icon: Settings, color: 'text-muted-foreground' },
  '.editorconfig': { icon: Settings, color: 'text-muted-foreground' },
  '.prettierrc': { icon: Settings, color: 'text-pink-400' },
  '.prettierignore': { icon: Settings, color: 'text-muted-foreground' },
  '.eslintrc': { icon: Settings, color: 'text-violet-500' },
  '.eslintrc.js': { icon: Settings, color: 'text-violet-500' },
  '.eslintrc.json': { icon: Settings, color: 'text-violet-500' },
  '.eslintrc.cjs': { icon: Settings, color: 'text-violet-500' },
  'eslint.config.js': { icon: Settings, color: 'text-violet-500' },
  'eslint.config.mjs': { icon: Settings, color: 'text-violet-500' },
  '.env': { icon: Shield, color: 'text-warning' },
  '.env.local': { icon: Shield, color: 'text-warning' },
  '.env.development': { icon: Shield, color: 'text-warning' },
  '.env.production': { icon: Shield, color: 'text-warning' },
  '.env.example': { icon: Shield, color: 'text-warning' },
  'package.json': { icon: Braces, color: 'text-success' },
  'package-lock.json': { icon: Lock, color: 'text-muted-foreground' },
  'yarn.lock': { icon: Lock, color: 'text-info' },
  'pnpm-lock.yaml': { icon: Lock, color: 'text-warning' },
  'bun.lockb': { icon: Lock, color: 'text-muted-foreground' },
  'Cargo.toml': { icon: Cog, color: 'text-warning' },
  'Cargo.lock': { icon: Lock, color: 'text-warning' },
  Gemfile: { icon: Gem, color: 'text-destructive' },
  'Gemfile.lock': { icon: Lock, color: 'text-destructive' },
  Makefile: { icon: Terminal, color: 'text-muted-foreground' },
  'CMakeLists.txt': { icon: Cog, color: 'text-info' },
  'tsconfig.json': { icon: Braces, color: 'text-info' },
  'jsconfig.json': { icon: Braces, color: 'text-warning' },
  'vite.config.ts': { icon: Flame, color: 'text-purple-500' },
  'vite.config.js': { icon: Flame, color: 'text-purple-500' },
  'webpack.config.js': { icon: Cog, color: 'text-info' },
  'tailwind.config.js': { icon: Hash, color: 'text-cyan-500' },
  'tailwind.config.ts': { icon: Hash, color: 'text-cyan-500' },
  'postcss.config.js': { icon: Cog, color: 'text-destructive' },
  'babel.config.js': { icon: Settings, color: 'text-warning' },
  '.babelrc': { icon: Settings, color: 'text-warning' },
  'README.md': { icon: BookOpen, color: 'text-info' },
  LICENSE: { icon: FileCheck, color: 'text-muted-foreground' },
  'LICENSE.md': { icon: FileCheck, color: 'text-muted-foreground' },
  'CHANGELOG.md': { icon: Scroll, color: 'text-info' },
  'requirements.txt': { icon: FileText, color: 'text-success' },
  'go.mod': { icon: Hexagon, color: 'text-cyan-500' },
  'go.sum': { icon: Lock, color: 'text-cyan-400' },
};

// Icon resolution is deterministic: exact filename, then .env prefixes, then extension, then fallback.
export function getFileIconData(filename: string): FileIconData {
  if (FILENAME_ICON_MAP[filename]) {
    return FILENAME_ICON_MAP[filename];
  }

  if (filename.startsWith('.env')) {
    return { icon: Shield, color: 'text-warning' };
  }

  const extension = filename.split('.').pop()?.toLowerCase();
  if (extension && FILE_ICON_MAP[extension]) {
    return FILE_ICON_MAP[extension];
  }

  return { icon: File, color: 'text-muted-foreground' };
}
